### PR TITLE
Allow to throw exception inside subscription in AsyncGenerator

### PR DESCRIPTION
**Pull request by dan-lee**
As of now, if an exception is thrown inside a subscription within an AsyncGenerator the exception will not be handled the same way as the other exceptions, remaining unhandled.

It will not reach the regular exception handling:

https://github.com/contra/graphql-helix/blob/e38b73a1fedcee021100bfff9fd253e5cc818f71/packages/core/lib/process-request.ts#L259-L270

This is probably because it happens inside an async function.

This PR changes this to be handled gracefully and returns the error result to the subscriber as a normal response.

Example use case which will be solved by this:

```ts
const resolvers = {
  Subscription: {
    onEvent: {
      subscribe: async function* () {
        if (someCondition()) {
          throw new Error('Not initialized')
        }
        yield something()
      }
    }
  }
}
```

### CODE REVIEW

**Comment by n1ru4l** [comment]
For reference in the future this is how subscribe errors are handled: https://github.com/graphql/graphql-js/blob/11a08024a35b08104b291627f4fdb2e8c69f8cab/src/execution/subscribe.ts#L165-L185

**Review by n1ru4l — APPROVED** [review]

**Review by n1ru4l — APPROVED** [review]

**Comment by n1ru4l** [comment]
@dan-lee Can you please add a changeset with the following contents? :)

```md
---
"graphql-helix": patch
---

Handle errors thrown by subscribe handlers.

Previously any error raised with a `subscribe` handler on the `Subscription` root type was not handled and forwarded to `formatPayload`, which could potentially lead to error message leaking to clients.
```

**Comment by dan-lee** [comment]
@n1ru4l Sure thing, I just did so. Thanks! :)

**Comment by dotansimha** [comment]
Available in graphql-helix@1.10.1

**Pull request merged**
